#### 1. Create a python program to find duplicate files by content. User will input path and it will scan all directories, sub-directories to find all duplicates files. Delete the found duplicate file.

In [1]:
import os
from pathlib import Path
from filecmp import cmp

DATA_DIR = Path("C:/Users/tsaluja/Python_Duplicate")
files = sorted(os.listdir(DATA_DIR))

# with the same content
duplicateFiles = []
  
# comparison of the documents
for file_x in files:
  
    if_dupl = False
  
    for class_ in duplicateFiles:
        # Comparing files having same content using cmp()
        # class_[0] represents a class having same content
        if_dupl = cmp(
            DATA_DIR / file_x,
            DATA_DIR / class_[0],
            shallow=False
        )
        if if_dupl:
            class_.append(file_x)
            break
  
    if not if_dupl:
        duplicateFiles.append([file_x])
print(duplicateFiles)


[['File1.txt', 'File2.txt'], ['Names.txt', 'Names2.txt']]


#### 2. Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters.Using these packages [random, strings]

In [7]:
import random
import string


for i in range(2):
    lower = string.ascii_lowercase
for i in range(2):
    digits = string.digits
for i in range(1):
    upper = string.ascii_uppercase
for i in range(1):
    special = string.punctuation
password = lower + upper + digits +special
var = random.sample(password,6)
pss="".join(var) 
print(pss)

p7UO3-


#### 3.Create 2D array and update the same 2D array provided that every prime number position should be replaced by cube of the positioned number.

In [114]:
import numpy as np
arr = np.arange(0,9).reshape(3,3)
def prime(n):
    count=0
    for i in range(1,10):
        if n%i==0:
            count+=1
    if count==2:
        return True
    else:
        return False

for i in range(3): 
    for j in range(3):
        if prime(i*3+j):
            arr[i,j]=(i*3+j)**3
print(arr)

[[  0   1   8]
 [ 27   4 125]
 [  6 343   8]]


#### 4.Python program to get the sum of every cubed value and its previous integer.

In [115]:
import numpy as np
arr = np.arange(0,16).reshape(4,4)
def prime(n):
    count=0
    for i in range(1,10):
        if n%i==0:
            count+=1
    if count==2:
        return True
    else:
        return False

for i in range(4): 
    for j in range(4):
        if prime(i*4+j):
            arr[i,j]=(i*4+j)**3+arr[i,j-1]
print(arr)


[[  0   1   9  36]
 [  4 129   6 349]
 [  8   9  10  11]
 [ 12  13  14  15]]


#### 5.	Given two arrays, find their intersection. Examples:

In [52]:
def intersection(a, b, n, m):
    i = 0
    j = 0
    while (i < n and j < m):
        if (a[i] > b[j]):
            j += 1
        else:
            if (b[j] > a[i]):
                i += 1
            else:
                # when both are equal
                print(a[i], end=" ")
                i += 1
                j += 1
a = [1, 3, 2, 3, 4, 5, 5, 6]
b = [3, 3, 5]
 
n = len(a)
m = len(b)
    
a.sort()
b.sort()

intersection(a, b, n, m)

3 3 5 

#### 6.	Create a 7 x 7  2D array having only multiples of 7. And return the last element of the same.

In [64]:
arr=np.zeros((7,7))
multiple=0
for i in range(7):
    for j in range(7):
        multiple+=7
        arr[i][j]=multiple
print(arr)
last=arr[-1,-1]
print("The last element obtained : ",last)

[[  7.  14.  21.  28.  35.  42.  49.]
 [ 56.  63.  70.  77.  84.  91.  98.]
 [105. 112. 119. 126. 133. 140. 147.]
 [154. 161. 168. 175. 182. 189. 196.]
 [203. 210. 217. 224. 231. 238. 245.]
 [252. 259. 266. 273. 280. 287. 294.]
 [301. 308. 315. 322. 329. 336. 343.]]
The last element obtained :  343.0


#### 7.	Checker Board Patten using Numpy:

In [6]:
import numpy as np
x = np.ones((5, 7))
x[1::2, 0::2] = 0 
x[0::2, 1::2] = 0
x

array([[1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.]])

#### 8.	Create a given Matrix:



In [33]:
# Alphabetic pattern using numpy
import numpy as np
x=int(input("Enter number of rows "))
y=int(input("Enter number of columns "))
arr=(['A','B','C','D'],
     ['E','F','G','H'],
     ['I','J','K','L'],
     ['M','N','O','P'],
     ['Q','R','S','T'],
     ['U','V','W','X'])

count=0
for i in range(x):
    for j in range(y):
        if arr[i][j] =='A' or arr[i][j] =='E' or arr[i][j] =='I' or arr[i][j] =='O' or arr[i][j] =='U':
            arr[i][j]=np.nan
            count+=1
print(np.matrix(arr))
print("The count of the missing values comes out to be :",count)

Enter number of rows 6
Enter number of columns 4
[['nan' 'B' 'C' 'D']
 ['nan' 'F' 'G' 'H']
 ['nan' 'J' 'K' 'L']
 ['M' 'N' 'nan' 'P']
 ['Q' 'R' 'S' 'T']
 ['nan' 'V' 'W' 'X']]
The count of the missing values comes out to be : 5
